### ISSUE TITLE
Sample should use either GET or POST, not both, probably just GET

### ISSUE THREAD

**Issue by baywet** [fabianwilliams/blazorwithgraphonazurefunct#2]
https://github.com/fabianwilliams/blazorwithgraphonazurefunct/blob/c2a2bf044af6586b80952986582b01e934c6cedc/MailbagSeriesFabs/ScopedForUsers/GraphUsers.cs#L23

**Comment by fabianwilliams** [comment]
resolved... only using get now

**Comment by baywet** [comment]
@fabianwilliams quick tip: if you write fix #issue number at the beginning of your commit it'll link it to this issue and close it automatically once the commit gets pushed to the main branch :)
