### ISSUE TITLE
use var or the type name, but do it consistently

### ISSUE THREAD

**Issue by baywet** [fabianwilliams/blazorwithgraphonazurefunct#4]
https://github.com/fabianwilliams/blazorwithgraphonazurefunct/blob/c2a2bf044af6586b80952986582b01e934c6cedc/MailbagSeriesFabs/ScopedForUsers/GraphUsers.cs#L58

**Comment by fabianwilliams** [comment]
fair.. I have updated most of them. the idea was to have an abstracted strongly typed object for the subset of information i needed but I didnt follow through on it. I will button up the rest later
