### ISSUE TITLE
Explanation of where the value for 'code=' is coming from is missing

### ISSUE THREAD

**Issue by roblom** [fabianwilliams/blazorwithgraphonazurefunct#7]
I have finally figured out that the value of "code" (in query strings) is the value of the "default" "function key" for the function being called. 
It is found in the Azure portal by opening the function and selecting the "Function keys" menu item under the "Developer"-section.

Also: please also update the blogpost which states nothing about this.
https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-mailbag-blazor-web-assembly-and-microsoft-graph-with-azure-functions/

Apart from this, thanks for a great post :-)

**Comment by fabianwilliams** [comment]
Thanks @roblom for the feedback. The bullet point at the top of the post regarding Azure Function spoke to anonymous v/s function code. I made a deliberate attempt as this post dealt with 3 very big topics to point to deeper explanations in existing articles and guidance but as it was in the code as well, i will add comments there for it in my next update. Cheers.
